baseURL = "https://pootytangfl.github.io/CTFWriteUps/"
languageCode = "en-us"
title = "CTF Write-Ups"
theme = "CactusPlus"

[params]
	author = "Andres Campuzano"
	description = "Documenting CTFs attempted"
	bio = "Reverse engineering the universe one step at a time"

	enableToc = true

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
        linkedin-square = "https://www.linkedin.com/in/acampuzanofl/"
	github-square = "https://github.com/pootytangfl"
